-- Criação da tabela de ingredientes
CREATE TABLE INGREDIENT (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL
);

-- Inserção dos ingredientes
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Pão', 0.80);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Carne', 3.00);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Queijo', 1.50);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Bacon', 2.50);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Alface', 0.50);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Tomate', 0.70);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Cebola', 0.60);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Ovo', 1.00);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Picles', 0.90);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Frango', 2.80);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Calabresa', 2.50);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Presunto', 1.80);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Milho', 0.80);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Ervilha', 0.80);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Hamburguer', 2.80);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Batata-Palha', 0.70);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Maionese', 0.50);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Mostarda', 0.50);
INSERT INTO INGREDIENT (NAME, PRICE) VALUES ('Catchup', 0.50);
